// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABlE0biFlXDkAyENFJ2yHUd8_SlbLbs6g',
    appId: '1:498716801442:web:29d640c04cba9c4252dafb',
    messagingSenderId: '498716801442',
    projectId: 'chat-app-b839b',
    authDomain: 'chat-app-b839b.firebaseapp.com',
    storageBucket: 'chat-app-b839b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApQdcC_JrEikrN50_yQQSfOzFdtn4CS-U',
    appId: '1:498716801442:android:ce9c1cfc0c8b28a352dafb',
    messagingSenderId: '498716801442',
    projectId: 'chat-app-b839b',
    storageBucket: 'chat-app-b839b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKVfMGE3AmQ3b4Z5U29-cVZxLv4ZaM5M',
    appId: '1:498716801442:ios:520b3ab1f539799352dafb',
    messagingSenderId: '498716801442',
    projectId: 'chat-app-b839b',
    storageBucket: 'chat-app-b839b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}